# Generated by Django 5.0.6 on 2024-06-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainJobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wishlist', 'wishlist'), ('applied', 'applied'), ('in progress', 'in progress'), ('offered', 'offered'), ('rejected', 'rejected')], max_length=200)),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('applied_date', models.DateField()),
                ('deadline', models.DateField()),
                ('url_link', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
