# Generated by Django 5.0.6 on 2024-06-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainjoblist',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mainjoblist',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mainjoblist',
            name='url_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
